import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = await readFile(resolve(root, 'src/client.js'), 'utf8')
const sourceCss = await readFile(resolve(root, 'src/skin.css'), 'utf8')

if (!source.includes('__EXHENTAI_CSS__')) {
  throw new Error('client source __EXHENTAI_CSS__ placeholder is missing')
}

const css = sourceCss

const body = source
  .replace('__EXHENTAI_CSS__', JSON.stringify(css))
const output = `// Generated by scripts/build-client.mjs; edit src/client.js and src/skin.css.\nwindow.__ModuleLoader__.load({\n  id: "ds-hentai",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n${body.split('\n').map((line) => (line.length > 0 ? `    ${line}` : '')).join('\n')}\n    return module.exports;\n  }\n});\n`

await writeFile(resolve(root, 'lib/client.js'), output, 'utf8')
console.log(JSON.stringify({
  moduleId: 'ds-hentai',
  sourceCssBytes: Buffer.byteLength(sourceCss),
  clientBytes: Buffer.byteLength(output)
}))
